name: Reject PR approval from committer

on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [synchronize]

# Declare required permissions for dismissing PR reviews
permissions:
  contents: read
  pull-requests: write

jobs:
  preventapprove:
    name: Reject PR approval by committers to the PR
    runs-on: ubuntu-latest
    steps:
      - name: Dismiss code reviews from committers
        uses: peckjon/reject-pr-approval-from-committer@1962a415b3c12f1ebe0104c9531ab577e5b0e3a9 # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
