name: Angular-Org Renovate

on:
  push:
    branches:
      # We do no run this on the default branch (main), as this is done by Renovate.
      - 'main'
  workflow_dispatch:
  # schedule:
  #   # Runs every 60 minutes.
  #   # This is the recommanded running time https://github.com/renovatebot/renovate/discussions/16658
  #   - cron: '0/60 * * * *'

# Declare default permissions as read only.
permissions:
  contents: read

env:
  COREPACK_ENABLE_DOWNLOAD_PROMPT: 0 # Disable corepack prompt

jobs:
  renovate:
    strategy:
      matrix:
        REPOSITORY:
          - alan-agius4/renovate-playground-git
    runs-on: ubuntu-latest
    steps:
      # Because the checkout and setup node action is contained in the dev-infra repo, we must
      # checkout the repo to be able to run the action we have created.  Other repos will skip
      # this step.
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: angular/dev-infra/github-actions/npm/checkout-and-setup-node@2c7bab7971084f3f1f6f72735099a9591ee5ebcb
      # TODO: Use pnpm/action-setup for pnpm install once pnpm is the packageManager for this repo
      - run: yarn --cwd .github/renovate install --immutable
        shell: bash
      - name: core
        run: |
          npm install corepack -g
          corepack enable

      - run: .github/renovate/node_modules/.bin/renovate
        env:
          LOG_LEVEL: debug
          RENOVATE_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
         # RENOVATE_FORK_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
          GITHUB_COM_TOKEN: ${{ secrets.NG_RENOVATE_USER_ACCESS_TOKEN }}
          RENOVATE_CONFIG_FILE: .github/renovate/runner-config.js
          RENOVATE_REPOSITORIES: ${{ matrix.REPOSITORY }}
